-- 0003_exercises.sql — comprehension questions and the writing task.
--
-- Additive, like every migration here: nothing is dropped or recreated.
--
-- Why a separate table rather than a JSON column on article_versions:
--
--  * the exercises are generated by their *own* call (prompts.EXERCISES_SYSTEM_PROMPT),
--    so they can be regenerated for an article that is already simplified and paid
--    for — which is the whole point of the split;
--  * that call has its own prompt version, stored on the version below, so
--    `--refresh-exercises` re-pays only for the rows whose questions are stale;
--  * one row per item keeps the reader's rendering simple and lets a question be
--    edited in place later without rewriting the article.
--
-- Kinds:
--   mcq      multiple choice — options is a JSON array, answer indexes it
--   short    open question   — sample is a model answer, key_points a checklist
--   writing  the writing task — prompt, key_points, model_answer, min_words

ALTER TABLE article_versions ADD COLUMN exercises_prompt_version TEXT NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS exercises (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    version_id      INTEGER NOT NULL REFERENCES article_versions (id) ON DELETE CASCADE,
    kind            TEXT    NOT NULL CHECK (kind IN ('mcq', 'short', 'writing')),
    ordinal         INTEGER NOT NULL DEFAULT 0,
    prompt          TEXT    NOT NULL,
    options         TEXT,                          -- JSON array; mcq only
    answer          INTEGER,                       -- index into options; mcq only
    why             TEXT    NOT NULL DEFAULT '',
    key_points      TEXT,                          -- JSON array; short and writing
    sample          TEXT    NOT NULL DEFAULT '',    -- model answer; short and writing
    min_words       INTEGER,                       -- writing only
    UNIQUE (version_id, kind, ordinal)
);

CREATE INDEX IF NOT EXISTS idx_exercises_version ON exercises (version_id, kind, ordinal);
